# YAML SELECTION CONFIG FILE
shuffle: False

Global:
  n_nodes:
    min: 10
    max: 5000

set_1:
  size_train: 500
  n_nodes:
    max: 100
  n_edges:
    quantiles: [0.5, 0.8]
set_2:
  size_validate: 50
  density:
    min: 0.1
    max: 0.5
set_3:
  size_validate: 400
  size_train: 2000
  density:
    min: 0.1
    max: 0.5
